### PR TITLE
More cleanup.

### PR DESCRIPTION
**Pull request by TrueUO**
More cleanup.

### CODE REVIEW

**Comment by TrueUO** [comment]
Do not merge. Going to fix the bugs for old Sonar.

Not touching all of those Code Smells right now though. I'll check a few out but most just hate our styles.

**Comment by TrueUO** [comment]
Alright fixed all but one. It looked fine to me.

**Comment by TrueUO** [comment]
Is there a way to remove the duplications warning from Sonar? We are going to have duplicates. Especially when just cleaning.

This is good to go, just need a review.

**Review by kevin-10 — APPROVED** [review]

**Comment by kevin-10** [comment]
Did i merge? You said don't merge. I dont remmeber if i did it lol.

**Pull request merged**
