### PR TITLE
Spawn fixes

### PR DESCRIPTION
**Pull request by Virulent16**
-Fixed spawn errors, that were made after "Create World" command. 
-Hires in Jhelom Dueling Pit were not correct. Compared with multiple shards on OSI, only hires available in Dueling Pit are fighters
- Added missing mobile, causing one of the errors, Jwilson.  Only a couple shards on OSI still spawn Jwilson.

"A slime named after Johnny Wilson, Chief Editor of Computer Gaming World (CGW), who gave UO the award for "Coaster of the Year" in 1998"

### CODE REVIEW

**Review by DocKnight86 — CHANGES_REQUESTED** [review]
Custom mobs or spawn changes can be made to your private branch. Won't be mergering with the current UO branch here, sorry.

**Comment by DocKnight86** [comment]
> Custom mobs or spawn changes can be made to your private branch. Won't be mergering with the current UO branch here, sorry.

Also TC is the best to get current spawn info as it is a fresh shard with out all the older EM/Seer occasional left over spawn.

**Comment by Virulent16** [comment]
Ahh okay! Sorry about that! I just like fixing the little things as I got along, so hoping the stuff here and there helps someone lol. Thank you for the info!

**Comment by DocKnight86** [comment]
> Ahh okay! Sorry about that! I just like fixing the little things as I got along, so hoping the stuff here and there helps someone lol. Thank you for the info!

I'd submit a pr to simply remove the Mob from the older spawn files if it's causing an error on a fresh spawn.

Otherwise the spawn files are really just a base. Everyone remembers UO a certain way and it's on the shard owners to populate the world or tweak spawners how they see fit.

**Comment by Virulent16** [comment]
@DocKnight86 There is 8 spawn errors with a fresh server, so that's a good idea. That makes sense to me now, not a bad idea to leave it like that then.

**Pull request closed without merging**
