### PR TITLE
Some warning fixes.

### PR DESCRIPTION
**Pull request by TrueUO**
https://dev.azure.com/argalep0304/TrueUO/_build/results?buildId=111&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=86dd5fa6-f51e-57a1-6dd4-575fd75fc7ef

### CODE REVIEW

**Comment by kevin-10** [comment]
I don't understand why we need to remove commented out code. Most the time, its not really code that's commented out, its good info we could use at later date when maintaining the code. If its a block of actual code, then sure, lets get rid of it, but informative comments are good IMO. As a matter of fact, I just added comments in this manner on that aggressor/aggressed code because you know at some point, that complicated shit needs to be deciphered.

**Comment by TrueUO** [comment]
It is not all // and it seems to only apply to the Ultima.dll folder and file.

**Comment by kevin-10** [comment]
Something like this, I understand: //Tex.WriteLine(System.String.Format("0x{0:X4} -> 0x{1:X4}", sum.index, index));

But something like this could be informative: bin.Write(itemheader[j++]); // header

**Comment by TrueUO** [comment]
Okay, I reverted that one.

**Comment by kevin-10** [comment]
See what I'm saying though? I dunno why it would ask you to remove that.

**Review by kevin-10 — APPROVED** [review]

**Pull request merged**
