### PR TITLE
Pet Disappearance

### PR DESCRIPTION
**Pull request by danielsheeper**
PetDisappearance

### CODE REVIEW

**Comment by DocKnight86** [comment]
If we are adding +1 like that dosent it effectively ignore the whole point of GetMaxStabled? 

You could overfill your stable every time. Tame a new pet, log out, tame another, log out. If full it should block adding, unless I am missing something here?

**Comment by danielsheeper** [comment]
> If we are adding +1 like that dosent it effectively ignore the whole point of GetMaxStabled?
> 
> You could overfill your stable every time. Tame a new pet, log out, tame another, log out. If full it should block adding, unless I am missing something here?

If you die in battle in the hunting ground, you move to the nearest healer for resurrection. If you log out and log in to summon the pet you were fighting with after resurrection, the pet disappears. In OSI, even if the stable stock is full, the pets you were hunting with will not disappear.

**Comment by DocKnight86** [comment]
Only as of the most recent patch. It seems they created a 3rd new "overflow" stable that handles it differently. Have you tested this on EA? 

When I Iog out with multiple pets I can't force my stable to hold more than it should, using that method.

With this new edit it appears you can on emulation.

**Comment by TrueUO** [comment]
@Argalep what do you think?

**Comment by danielsheeper** [comment]
> Only as of the most recent patch. It seems they created a 3rd new "overflow" stable that handles it differently. Have you tested this on EA?
> 
> When I Iog out with multiple pets I can't force my stable to hold more than it should, using that method.
> 
> With this new edit it appears you can on emulation.

Did you mean pub 111? The changes in the recent patch are known to be related to pack animals and pets that are not bonded.

**Comment by danielsheeper** [comment]
I have fixed this in another method.

**Comment by TrueUO** [comment]
@danielsheeper when ever you get some time, mind explaining exactly what the issue is and what this fixes?

**Pull request closed without merging**
