### PR TITLE
Update ItemPropertyInfo.cs

### PR DESCRIPTION
**Pull request by Argalep**
ReactiveParalyze exists as AOSWeaponAttribute. I remove the unnecessary.

### CODE REVIEW

**Comment by kevin-10** [comment]
It exists on AosArmorAttributes as well. You can get it on two handed weapons and shields. This update would be wrong.

**Comment by Argalep** [comment]
Does the following code work for two-handed weapons?

`Register(206, new ItemPropertyInfo(AosWeaponAttribute.ReactiveParalyze, 1154660, 140, 0, 1, 1, 1152400,
                 new PropInfo(1, 0, 1)));`

I remove the weapon in the AosArmorAttribute.ReactiveParalyze definition. BaseWeapon does not cover AosArmorAttribute after all.

image

So By the way, if you look at the picture, Reactive Paralyze Armor is 220, not 207.

**Comment by kevin-10** [comment]
> Does the following code work for two-handed weapons?
> 
> `Register(206, new ItemPropertyInfo(AosWeaponAttribute.ReactiveParalyze, 1154660, 140, 0, 1, 1, 1152400, new PropInfo(1, 0, 1)));`
> 
> I remove the weapon in the AosArmorAttribute.ReactiveParalyze definition. BaseWeapon does not cover AosArmorAttribute after all.
> 

AosWeaponAttrribute has ReactiveParalyze:
https://github.com/TrueUO/TrueUO/blob/a0c990296f16348898eee90050f5e9c36aa14e40/Scripts/Misc/AOS.cs#L1260

Therfore, removing it from weapons is not correct as it has a chance to spawn in certain conditions on two handed weapons.

**Comment by kevin-10** [comment]
And 206 is for reactive paralyze in weapon properties, 220 is for reactive paralyze in armor properties for shields. This is also correct. If its not spawning correctly, then we'll hav eto figure out why but this isnt the reason.

**Comment by kevin-10** [comment]
so, change 207 to 220, I gotcha. Close this PR out so the other changes arent added in.

**Pull request closed without merging**
