### PR TITLE
Imbuing Fix.

### PR DESCRIPTION
**Pull request by Argalep**
- skills intensity issue fix
- Correct material to HCI and DCI weapon type

### CODE REVIEW

**Comment by kevin-10** [comment]
Why is the skill bonus scale being changed from 5 to 1? On loot, it is in increments of 5.

**Comment by TrueUO** [comment]
It depends on the weapon type being ranged or not.

A video is on the trueuo bug forums.

**Comment by Argalep** [comment]
> Why is the skill bonus scale being changed from 5 to 1? On loot, it is in increments of 5.

I focused on the Imbuing menu.

**Comment by kevin-10** [comment]
what about weapons?

**Comment by kevin-10** [comment]
See the staff discord. Im going to push this fix but ill have to fix the loot scale.

**Review by kevin-10 — APPROVED** [review]

**Pull request merged**
