### PR TITLE
First round of Sonar fixes.

### PR DESCRIPTION
**Pull request by TrueUO**

### CODE REVIEW

**Comment by kevin-10** [comment]
Did you test the ECHandleInput? Changing the formatting for gump packets may have bad results.

**Comment by TrueUO** [comment]
> Did you test the ECHandleInput? Changing the formatting for gump packets may have bad results.

https://sonarcloud.io/project/issues?id=trueuo&open=AXQR3rYHb7GOYmlb_-gN&pullRequest=323&resolved=false&types=CODE_SMELL

Because composite format strings are interpreted at runtime, rather than validated by the compiler, they can contain errors that lead to unexpected behaviors or runtime errors. This rule statically validates the good behavior of composite formats when calling the methods of String.Format, StringBuilder.AppendFormat, Console.Write, Console.WriteLine, TextWriter.Write, TextWriter.WriteLine, Debug.WriteLine(String, Object[]), Trace.TraceError(String, Object[]), Trace.TraceInformation(String, Object[]), Trace.TraceWarning(String, Object[]) and TraceSource.TraceInformation(String, Object[]).

s = string.Format("foo"); // Noncompliant, there is no need to use string.Format here.


But no I do not have the EC on my current laptop. I will revert that one if you think it makes it an issue.

**Comment by TrueUO** [comment]
public override string Compile()
		{
			return string.Format("{{ echandleinput }}");
			return "echandleinput";
		}

basically, since we know it is a string already by the public call it knows what it is looking for if we use "" and does not need to be told twice, is what I got out of it.

**Comment by kevin-10** [comment]
I dunno, that needs to be tested. other string inputs for gumps use brackets. Maybe remove the string.format() and just put "{{ echandleinput }}"

**Pull request closed without merging**
