### PR TITLE
BaseCreature Spell Bug fix.

### PR DESCRIPTION
**Pull request by Argalep**
* Stuck in spells can occur in creatures with magic ability.

### CODE REVIEW

**Comment by kevin-10** [comment]
This fix isn't understanding the problem. FinishSequence needs to be called in the spell timer:

https://github.com/TrueUO/TrueUO/blob/dad69af8c2a340aa9d497f19957330616b8f2664/Scripts/Spells/Base/Spell.cs#L1292

**Comment by Argalep** [comment]
> This fix isn't understanding the problem. FinishSequence needs to be called in the spell timer:
> 
> https://github.com/TrueUO/TrueUO/blob/dad69af8c2a340aa9d497f19957330616b8f2664/Scripts/Spells/Base/Spell.cs#L1292

in some cases this function does not work and the creature stops casting spells. Mobile.Spell always has spell when I check it.  Also, if you look at the last time the creature died, it points to times similar to NextCast time.



**Not : The debug message written on the pet at the time of the problem is according to the code below.**

m_Mobile.DebugSay("{0} - {1} - {2}", m_Mobile.Spell, NextCastTime, DateTime.Now > NextCastTime);

**Comment by kevin-10** [comment]
Right, and we need to fix this at the core of the solution, which is what I pointed out. If the mobile is dead at the time the timer casts the spell, it simply removes the spell from the timer. It needs to complete the spell sequence, which removes the spell from the mobiles Spell property.

So after registry.RemoveAt(i); it needs a spell.FinishSequence()

**Comment by Argalep** [comment]
> So after registry.RemoveAt(i); it needs a spell.FinishSequence()

Isn't there a crash problem for the parameter Spell.Caster is null?

**Comment by kevin-10** [comment]
Why would the caster be null?

**Review by kevin-10 — APPROVED** [review]

**Pull request merged**
