### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by TrueUO**
Removes a few left over quest items from already removed "legacy" quests.

### CODE REVIEW

**Review by kevin-10 — APPROVED** [review]

**Comment by kevin-10** [comment]
Only concern is, on servers where players legit got these items when these quests were active.

**Review by kevin-10 — APPROVED** [review]

**Comment by TrueUO** [comment]
Yeah but the horn and Sextant were coded for use with much older quests. They are drag and drop so if anyone needs to keep they can just move over to their customs folder.

**Comment by kevin-10** [comment]
Are they rewards or items needed to do the quest?

**Comment by TrueUO** [comment]
The enchanted sextant came from an old Haven quest, from before it was destroyed. The horn was a quest item as part of a quest that was already removed.

**Pull request merged**
