### PR TITLE
RegionCleanup

### PR DESCRIPTION
**Pull request by TrueUO**
- One method cleanup allowed a simplify of a method in BaseVendor.

### CODE REVIEW

**Comment by TrueUO** [comment]
Good to go.

**Comment by kevin-10** [comment]
If the method is marked virtual, we shouldn't remove an argument that could be used if the method is overridden in the future.

**Comment by TrueUO** [comment]
> If the method is marked virtual, we shouldn't remove an argument that could be used if the method is overridden in the future.

Can you point me to a recent example, please?

**Comment by kevin-10** [comment]
CheckVendorAccess(this, from)

There is no need to remove the first argument. Though its not used, it may be in the future.

**Comment by TrueUO** [comment]
Alright, going to re-add that part.

**Comment by kevin-10** [comment]
Not a big deal but its easier to leave it in than to have to change it again. Of course, others could be using it this way with custom code as well.

**Review by kevin-10 — APPROVED** [review]

**Pull request merged**
